### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by miliu99** [uglow/active-win-log#1]
I just tried it. It started ok and give no errors, but it doesn't track active win. The only thing I see in awl.json is 
{
  "pid": 88124,
  "stats": {}
}

**Comment by codewaseem** [comment]
Same here.

**Comment by abjagtap** [comment]
facing the same issue

**Comment by andyg2** [comment]
Same issue here too, please advise

**Comment by arpadcseh** [comment]
Yep me too. Only the main dependency needs an update
```
-    "active-win": "4.1.0",
+    "active-win": "6.3.0",
```
to get it work. 
Would be good the get it updated @uglow . In the meantime hope the manual update is useful for others as well.
And thanks for the package :)

**Comment by uglow** [comment]
Sorry folks - GitHub seems to bury the important notifications. I'll look at this in the next few days.

**Comment by uglow** [comment]
As @arpadcseh mentioned, updating the active-win dependency seems to make it work. OSX 10.15 brought changes that broke the previous behaviour. See https://github.com/sindresorhus/active-win/issues/97 for possible solutions.
